#!/bin/bash

SECRET=$SECRET DBNAME=$DB_NAME DBURL=$DB_URL PORT=80 MONGOOSEDEBUG=$DB_DEBUG ADMINEMAIL=$ADMIN_EMAIL ADMINPASSWORD=$ADMIN_PASSWORD STATIC="./static" TEMPLATE_PATH="/template.yml" TBA_KEY=$TBA_KEY TBA_HMAC=$TBA_HMAC FIELDIMG="/field" node ./index.js
