version: '3.3'

services:
    mongodb:
        image: mongo:4.2.2
        container_name: mongodb-global-database
        hostname: mongodb-global-database
        restart: always
        # store mongodb data in a local dir
        volumes:
            - "./mongodata:/data/db"
        environment:
            # set mongodb root username/password
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example-password
        networks:
            - strangescout_main
        labels:
            # set as a tcp service in traefik (don't change)
            - traefik.tcp.routers.mongodb.entrypoints=mongodb
            - traefik.tcp.routers.mongodb.rule=HostSNI(`*`)

networks:
    strangescout_main:
        external: true