version: '3.3'

services:
    strangescout:
        # whatever you've tagged the built strangescout image
        image: theredalliance/strangescout:latest
        container_name: ss-offseason
        hostname: ss-offseason
        restart: always
        
        environment:
            # secret used to encrypt jwts
            - SECRET=<jwt-secret>
            # uri of the database
            # <db-password>: password for mongodb set in the mongodb compose file
            # <dbname>: database name to store data in
            - "DB_URL=mongodb://root:<db-password>@mongodb-global-database:27017/<dbname>?authSource=admin"
            # log some extra mongoose info
            - DB_DEBUG=<true/false>
            # email for the default admin account
            - ADMIN_EMAIL=<email@yourdomain.tld>
            # password for the default admin account
            - ADMIN_PASSWORD=<supersecretpassword>
            # TBA_HMAC key
            - TBA_HMAC=<tba_hmac_key>
        volumes:
            - ./template.yml:/template.yml
        networks:
            - strangescout_main
        labels:
            # domain we're hosted on
            - traefik.http.routers.strangescout.rule=Host(`<yourdomain.tld>`)
            # set router
            - traefik.http.routers.strangescout.entrypoints=websecure
            # automatic tls certificates
            - traefik.http.routers.strangescout.tls.certresolver=leresolver
            # enable compression
            - traefik.http.routers.strangescout.middlewares=compress

networks:
    strangescout_main:
        external: true