name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p '${{ secrets.DOCKER_PASSWORD }}'
    - uses: whoan/docker-build-with-cache-action@v2
      with:
        username: "${{ secrets.DOCKER_USER }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: theredalliance/strangescout
        image_tag: latest
    - name: Tag the Docker image
      run: docker tag theredalliance/strangescout:latest theredalliance/strangescout:$(git rev-parse --short "$GITHUB_SHA")
    - name: Push the Docker image
      run: docker push theredalliance/strangescout
